spring:
  application:
    name: spring-cloud-producer
server:
  port: 9000
eureka:
  instance:
    instance-id: 用户行为数据服务
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://152.136.110.205:8000/eureka/,http://152.136.110.205:8001/eureka/,http://152.136.110.205:8002/eureka/