spring:
  datasource:
    username: curry
    password: Ocean1109
    url: jdbc:postgresql://152.136.110.205:8081/shopping
    driver-class-name: org.postgresql.Driver
  application:
    name: spring-cloud-producer
server:
  port: 9000
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 152.136.110.205
  client:
    service-url:
      defaultZone: http://152.136.110.205:8000/eureka/,http://152.136.110.205:8001/eureka/,http://152.136.110.205:8002/eureka/


#mybatis-plus配置控制台打印完整带参数SQL语句
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
